export const THEME = {
  LIGHT: {
    text: {
      primary: "#22312E",
      secondary: "#666666",
    },
    button: {
      secondary: "#F2F2F2",
    },
    bellBackground: "#E8E8E8",
    headerTextColor: "#666666",
    inputPlaceholderColor: "#CDCDCD",
    inputTextColor: "#707070",
    background: "#FCFCFC",
    secondary: "#868686",
    descriptionTextColor: "#666666",
    actionBackground: "#00CED114",
    primary: "#13478b",
    inputTextFieldBorderColor: "#dee2e6",
    disabled: "#CDCDCD",
    backgroundPlus: "#00CED1",
    green: "#27AE60",
    red: "#E65464",
    orange: "#F08D3B",
    InputPlaceholderColor: "#C3C3C3",
    InputTextColor: "#707070",
    LoginFormBoxBackground: "#ffffff",
    LoginFormLogoTextColor: "#ffffff",
    HeadingTextColor: "#2980b9",
    SubHeadingTextColor: "#707070",
    CreditGreen: "#1DAE81",
    DebitRed: "#AE1D1D",
  },
  DARK: {
    text: {
      primary: "#ffffff",
      secondary: "#CCCCCC",
    },
    button: {
      secondary: "#0C2133",
    },
    descriptionTextColor: "#666666",

    actionBackground: "#00CED114",
    bellBackground: "#0C2133",
    background: "#0D1225",
    inputPlaceholderColor: "#C3C3C3",
    inputTextColor: "#707070",
    loginFormBoxBackground: "#ffffff",
    loginFormLogoTextColor: "#ffffff",
    primary: "#13478b",
    secondary: "#707070",
    backgroundPlus: "#00CED1",
    headerTextColor: "#ffffff",
    InputPlaceholderColor: "#C3C3C3",
    InputTextColor: "#707070",
    LoginFormBoxBackground: "#ffffff",
    LoginFormLogoTextColor: "#ffffff",
    HeadingTextColor: "#1DAE81",
    SubHeadingTextColor: "#707070",
    CreditGreen: "#1DAE81",
    DebitRed: "#AE1D1D",
  },
};
